name: "Changelog Generator"
description: "Generate a changelog based on commit messages"
inputs:
  token:
    description: 'GitHub token'
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Check Quality
      uses: Jasviers/actions/source-analysis/quality-checks@v1
      with:
        language: none
        skip-hadolint: 'true'

    - name: Make Release
      uses: googleapis/release-please-action@v5
      with:
        token: ${{ inputs.token }}