name: "Changelog Generator"
description: "Generate a changelog based on commit messages"
inputs:
  token:
    description: 'GitHub token'
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check Quality
      uses: Jasviers/actions/source-analysis/quality-checks@v1
      with:
        language: none

    - name: Make Release
      uses: googleapis/release-please-action@v4
      with:
        token: ${{ inputs.token }}
        release-type: simple
        changelog-types: >-
          [
            {"type": "feat", "section": "✨ Features", "hidden": false},
            {"type": "fix", "section": "🐛 Fixes", "hidden": false},
            {"type": "chore", "section": "🧹 Chores", "hidden": true},
            {"type": "docs", "section": "📚 Documentation", "hidden": false},
            {"type": "refactor", "section": "🛠 Refactors", "hidden": false}
          ]