name: GO code security

on:
  workflow_call:

jobs:
  codeSecurity:
    - name: Snyk Check
        uses: snyk/actions@master
        with:
          args: --file=go.mod
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Secret Detection
        uses: github/secret-scanning@v1