name: Go linting

on:
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Linting (golangci-lint)
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
          golangci-lint run