name: Spell check

on:
  workflow_call:

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Spellcheck
        uses: codespell-project/actions-codespell@v2
