name: "Security Checks"
description: "Check source code for security vulnerabilities using Snyk and Trivy"

inputs:
  snyk-token:
    description: 'Snyk token for authentication'
    required: true
  github-token:
    description: 'GitHub token for uploading SARIF results'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Snyk
      shell: bash
      run: npm install -g snyk

    - name: Authenticate Snyk
      shell: bash
      run: snyk auth ${{ inputs.snyk-token }}

    - name: Snyk Check
      shell: bash
      run: snyk code test --sarif > snyk-code.sarif || true

    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v4
      continue-on-error: true
      with:
        sarif_file: snyk-code.sarif
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Upload Snyk artifact
      uses: actions/upload-artifact@v3
      with:
        name: snyk-sarif
        path: snyk-code.sarif

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: "${{ steps.meta.outputs.tags }}"
        format: "template"
        template: "@/contrib/sarif.tpl"
        output: "trivy-results.sarif"
        severity: "CRITICAL,HIGH"

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v4
      continue-on-error: true
      with:
        sarif_file: "trivy-results.sarif"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
  
    - name: Upload Trivy SARIF artifact
      uses: actions/upload-artifact@v3
      with:
        name: trivy-sarif
        path: trivy-results.sarif