name: "Changelog Generator"
description: "Generate a changelog based on commit messages"
runs:
  using: "composite"
  steps:
    - name: Check Quality
      uses: Jasviers/actions/source-analysis/quality-checks@v1
      with:
        languaje: none

    - name: Make Release
      uses: google-github-actions/release-please-action@v4
      with:
        release-type: simple
        changelog-types: >-
          [
            {"type": "feat", "section": "✨ Features", "hidden": false},
            {"type": "fix", "section": "🐛 Fixes", "hidden": false},
            {"type": "chore", "section": "🧹 Chores", "hidden": true},
            {"type": "docs", "section": "📚 Documentation", "hidden": false},
            {"type": "refactor", "section": "🛠 Refactors", "hidden": false}
          ]