name: Go pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
  workflow_call:

jobs:
  Go:
    runs-on: ubuntu-latest
    steps:
      # Source Stage
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.17"

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Spellcheck
        uses: codespell-project/actions-codespell@v2

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          sonar.projectKey: "jasviers"
          sonar.organization: "lakasa"

      - name: Snyk Check
        uses: snyk/actions@master
        with:
          args: --file=go.mod
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
