name: Go pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
  workflow_call:

jobs:
  SourceAnalysis:
    runs-on: ubuntu-latest
    steps:
      # Source Stage
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.17"

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Spellcheck
        uses: codespell-project/actions-codespell@v2

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=jasviers_${{ github.event.repository.name }}
            -Dsonar.organization=jasviers
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.branch.name=${{ github.ref_name }}

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Check
        run: snyk test --file=go.mod


  BuildAndTest:
    runs-on: ubuntu-latest
    needs: SourceAnalysis
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.17"

      - name: Build Go Application
        run: go build -o app

      - name: Run Unit Tests and Coverage
        run: |
          if [ -d test ] || [ -d tests ]; then
            go test ./... -coverprofile=coverage.out
            go tool cover -func=coverage.out | awk '/^total:/ { if ($3 < 80) exit 1; }'
          fi

      - name: Build Docker Image
        run: docker build -t ${{ github.event.repository.name }} .

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        continue-on-error: false
