name: Go pipeline

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  Source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Linting
        uses: ./.github/workflows/source/go-linting.yml

      - name: Spell check
        uses: ./.github/workflows/source/spellcheck.yml
