name: Kubernetes pipeline

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      language: kubernetes
      run-docker-build: false
    secrets: inherit
